# Site settings
title: Tech+Earth
subtitle: Tools for sustainable development
email: daniel@mcquilleninteractive.com
description: News on technology in sustainability.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: 
city: 
state: Tasmania
zip_code: 7008
country: Australia
phone: 

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# Build settings
markdown: kramdown
